version: '3'
services:
  db:
    container_name: database
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test

  backend:
    container_name: account_api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

